// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxmFM3tT3R-TFK2q77k1rkIUK1QO5qniE',
    appId: '1:113240586146:android:3dbd9833a799bd3599e4fb',
    messagingSenderId: '113240586146',
    projectId: 'redditclone-bbbe6',
    databaseURL: 'https://redditclone-bbbe6-default-rtdb.firebaseio.com',
    storageBucket: 'redditclone-bbbe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGobF4WHXL8ENjsqkUhMn6PWgCZmobl4o',
    appId: '1:113240586146:ios:fb9f12bbe45dae6a99e4fb',
    messagingSenderId: '113240586146',
    projectId: 'redditclone-bbbe6',
    databaseURL: 'https://redditclone-bbbe6-default-rtdb.firebaseio.com',
    storageBucket: 'redditclone-bbbe6.appspot.com',
    iosClientId: '113240586146-rg0ltr86nilhqokf4sb17jsheo29va4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
